### ISSUE TITLE
Add dokku_letsencrypt library

### ISSUE THREAD

**Issue by decentral1se** [dokku/ansible-dokku#54] opened 2020-03-09 12:30 UTC
Opening this up to track, will be very useful to add.

**Comment by decentral1se** [comment] 2020-03-15 11:15
See https://github.com/dokku/ansible-dokku/pull/49.

**Comment by ltalirz** [comment] 2020-07-15 09:54
Thanks for the PR! I'm closing this as a duplicate of #9 (will mention your PR there).

**Closed by ltalirz** 2020-07-15 09:54 UTC
